version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pg_db
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"